### PR TITLE
feat: implement landing page

### LINKED ISSUE #6: Landing Page Implementation
#### **Is your feature request related to a problem? Please describe.**  
The current lack of a visually appealing and intuitive landing page makes it challenging to introduce new users to Vibestart’s mission and features effectively. As a result, potential users might lose interest or fail to understand the value proposition of the platform.

#### **Describe the solution you'd like**  
A responsive and modern landing page built with **ShadCN UI**, featuring:  
1. **Hero Section**:  
   - A bold introduction with the tagline: *"Join the rhythm of Indian hip-hop."*  
   - Call-to-action buttons: *“Join an E-Cypher”* and *“Explore Community”*.  
   - Background visuals: Subtle, dynamic animations that reflect urban hip-hop culture (graffiti-style graphics, vinyl record elements).  

2. **Features Section**:  
   - A three-column layout showcasing core features like:  
     - **Join Online E-Cyphers**: Engage with real-time group freestyles.  
     - **Share Your Work**: Upload and showcase tracks or videos.  
     - **Connect with Artists**: Build your network within the hip-hop community.  

3. **Testimonials Section**:  
   - Carousel featuring quotes and feedback from early users/artists.  

4. **Footer**:  
   - Quick links to social media, terms of service, and contact information.  

#### **Describe alternatives you've considered**  
1. **Using another UI framework** like Material UI or Tailwind directly. However, ShadCN UI provides a clean, accessible, and component-driven architecture that aligns with the needs of a community-based app.  
2. **Simpler Landing Page**: Focus only on text and static images, but this lacks the dynamic appeal necessary to captivate users in a competitive digital space.  

#### **Additional context**  
- ShadCN UI ensures component reusability, making future iterations of the landing page easier to manage.

### PR DESCRIPTION
**Pull request by saumyasharma810**
implemented a basic landing page

fix #6

Fixes #6 

## Description of the changes

-
-
-

### CODE REVIEW

**Comment by 0xsarwagya** [comment]
1. Conflicts in package-lock.json & package.json :)
2. Please Remove Unnecessary Commented Codes
3. Use <Link /> instead of <a />

**Comment by 0xsarwagya** [comment]
Hey @saumyasharma810 Please use <Link> from next/link instead of <a> Tag

**Review by utkarsh314 — APPROVED** [review]
LGTM

**Comment by 0xsarwagya** [comment]
@utkarsh314 @saumyasharma810 

Locally Not Working :)

- Link Tag Instead Of Anchor Tags
- Unused Comments

**Pull request closed without merging**
